networks:
  investbrain-network:
    driver: bridge
services:
  app:
    image: investbrainapp/investbrain:latest
    container_name: investbrain-app
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-8000}:80"
    environment:
      - APP_KEY= # Generate a key using `openssl rand -base64 32`
      - APP_URL="http://localhost:8000"
      - ASSET_URL="http://localhost:8000"
      - DB_CONNECTION=mysql
      - DB_HOST=investbrain-mysql
      - DB_PORT=3306
      - DB_DATABASE=investbrain
      - DB_USERNAME=investbrain
      - DB_PASSWORD=investbrain
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - REDIS_HOST=investbrain-redis
    volumes:
      - ./storage:/var/www/app/storage:delegated
    depends_on:
      - mysql
      - redis
    networks:
      - investbrain-network
  redis:
    image: redis:alpine
    container_name: investbrain-redis
    restart: unless-stopped
    tty: true
    networks:
      - investbrain-network
    volumes:
      - investbrain-redis:/data
  mysql:
    image: mysql:8.0
    container_name: investbrain-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-investbrain}
      MYSQL_USER: ${DB_USERNAME:-investbrain}
      MYSQL_PASSWORD: ${DB_PASSWORD:-investbrain}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-investbrain}
    command: 
      - --cte-max-recursion-depth=25000
    volumes:
      - investbrain-mysql:/var/lib/mysql
    networks:
      - investbrain-network
volumes:
  investbrain-redis:
  investbrain-mysql:
