name: Build and push Docker images

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.11.0
           docker/Dockerfile

      - name: Extract version from tag
        id: extract-version
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ./docker/Dockerfile
          push: true
          tags: |
            investbrainapp/investbrain:latest
            investbrainapp/investbrain:${{ env.version }}
            ghcr.io/investbrainapp/investbrain:latest
            ghcr.io/investbrainapp/investbrain:${{ env.version }}


